name: Deploy to EC2

on:
  push:
    branches:
      - main # 또는 프로젝트에 맞는 브랜치

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t yourusername/cwu-ai:latest ./path/to/Dockerfile
        docker push yourusername/cwu-ai:latest
        # cwu-front에 대해서도 동일한 단계를 반복

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd path/to/your/project
          docker-compose pull
          docker-compose up -d
